openapi: 3.0.3
info:
  title: Versioning API
  version: "1.0.0"
servers:
  - url: "https://your-api-id.execute-api.region.amazonaws.com/Prod"
paths:
  /api/create:
    post:
      summary: "Create a new application record"
      operationId: createApp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                app_name:
                  type: string
                  description: "The name of the application"
                secure:
                  type: boolean
                  default: false
                  description: "Whether the app requires secure token access"
                expiry_days:
                  type: integer
                  default: 365
                  description: "Number of days the token remains valid"
      responses:
        "201":
          description: "Application created successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  app_name:
                    type: string
                  version:
                    type: string
                  token:
                    type: string
                    nullable: true
        "400":
          description: "Bad request if required fields are missing or invalid"
        "409":
          description: "Conflict if the application already exists"
        "500":
          description: "Internal server error"
  /api/{app_name}/version:
    get:
      summary: "Retrieve the current version of the application"
      operationId: getVersion
      parameters:
        - name: app_name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Version retrieved successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
        "404":
          description: "Application not found"
        "500":
          description: "Internal server error"
  /api/{app_name}/bump:
    post:
      summary: "Bump the application's version"
      operationId: bumpVersion
      parameters:
        - name: app_name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum: ["major", "minor", "patch"]
                  description: "Type of version increment"
      responses:
        "200":
          description: "Version bumped successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  new_version:
                    type: string
        "400":
          description: "Invalid request parameters"
        "404":
          description: "Application not found"
        "500":
          description: "Internal server error"
  /api/{app_name}/set:
    post:
      summary: "Set the application's version directly"
      operationId: setVersion
      parameters:
        - name: app_name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                new_version:
                  type: string
                  description: "New version to set directly (must be major.minor.patch format)"
      responses:
        "200":
          description: "Version set successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  new_version:
                    type: string
        "400":
          description: "Invalid request parameters or missing new version"
        "500":
          description: "Internal server error"
components:
  securitySchemes:
    BearerAuth:
      type: "http"
      scheme: "bearer"
      bearerFormat: "JWT"
security:
  - BearerAuth: []
