name: Deploy SAM Application

on:
  push:
    branches:
      - "*/*" # matches every branch containing a single '/'
      - "*"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      python-version: "3.12"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ steps.setup.outputs.python-version }}

  run_tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ needs.setup.outputs.python-version }}

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install awscli boto3 aws-sam-cli pytest pytest-mock moto==3.0.7 PyJWT==2.3.0

      - name: Run Unit Tests
        run: |
          python -m pytest ./tests/test_lambda_function_e2e.py

  build_application:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - name: Build SAM Application
        run: sam build

  deploy_application:
    needs: build_application
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy SAM Application
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name versioning-app --capabilities CAPABILITY_IAM --region ${{ secrets.AWS_REGION }} --resolve-s3

  verify_deployment:
    needs: deploy_application
    runs-on: ubuntu-latest
    steps:
      - name: Verify deployment
        run: echo "Deployed Successfully"
